name: "Podcast Generator"
author: "Jeeven"
description: "Generates a feed for podcasts from YAML file"
runs:
 using: "docker"
 image: "Dockerfile"
branding:
 icon: "git-branch"
 color: "red"
inputs:
 email:
  description: The commtiter's email address
  required: true
  default: ${{github.actor}}@localhost
name:
 description: The committer's name
 required: true
 default: ${{github.actor}}
 